
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Configuración de Supabase
const SUPABASE_URL = 'https://whjqvtvkuyucxsmwkthb.supabase.co'
const SUPABASE_PUBLISHABLE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndoanF2dHZrdXl1Y3hzbXdrdGhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMzc5MjQsImV4cCI6MjA1OTcxMzkyNH0.AXL4UnlZLaTdfocWAXoD6oPM5NyDLVaTTBNb4AmxYyU'

// Cliente de Supabase correctamente configurado para la aplicación
// Incluye soporte para la base de datos tipada con TypeScript
export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);

// Para utilizar el cliente en cualquier componente:
// import { supabase } from "@/integrations/supabase/client";
